#!/bin/bash

source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/bin/linux/gfx-funcs.sh"
source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/bin/linux/git-funcs.sh"

gfx_section_start "Reindexing LL Game Server Repos"

# Game Server Repos
git_clone "https://github.com/LacledesLAN/gamesvr-7daystodie" "./repos/gamesvr-7daystodie"
git_clone "https://github.com/LacledesLAN/gamesvr-7daystodie-freeplay" "./repos/gamesvr-7daystodie-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-blackmesa" "./repos/gamesvr-blackmesa"
git_clone "https://github.com/LacledesLAN/gamesvr-blackmesa-freeplay" "./repos/gamesvr-blackmesa-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-csgo" "./repos/gamesvr-csgo"
git_clone "https://github.com/LacledesLAN/gamesvr-csgo-freeplay" "./repos/gamesvr-csgo-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-csgo-test" "./repos/gamesvr-csgo-test"
git_clone "https://github.com/LacledesLAN/gamesvr-csgo-tourney" "./repos/gamesvr-csgo-tourney"
git_clone "https://github.com/LacledesLAN/gamesvr-csgo-warmod" "./repos/gamesvr-csgo-warmod"
git_clone "https://github.com/LacledesLAN/gamesvr-cssource" "./repos/gamesvr-cssource"
git_clone "https://github.com/LacledesLAN/gamesvr-cssource-freeplay" "./repos/gamesvr-cssource-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-dods" "./repos/gamesvr-dods"
git_clone "https://github.com/LacledesLAN/gamesvr-dods-freeplay" "./repos/gamesvr-dods-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-factorio" "./repos/gamesvr-factorio"
git_clone "https://github.com/LacledesLAN/gamesvr-fof" "./repos/gamesvr-fof"
git_clone "https://github.com/LacledesLAN/gamesvr-garrysmod" "./repos/gamesvr-garrysmod"
git_clone "https://github.com/LacledesLAN/gamesvr-gesource" "./repos/gamesvr-gesource"
git_clone "https://github.com/LacledesLAN/gamesvr-gesource-freeplay" "./repos/gamesvr-gesource-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-goldsource" "./repos/gamesvr-goldsource"
git_clone "https://github.com/LacledesLAN/gamesvr-goldsource-cstrike" "./repos/gamesvr-goldsource-cstrike"
git_clone "https://github.com/LacledesLAN/gamesvr-goldsource-dmc" "./repos/gamesvr-goldsource-dmc"
git_clone "https://github.com/LacledesLAN/gamesvr-goldsource-hldm" "./repos/gamesvr-goldsource-hldm"
git_clone "https://github.com/LacledesLAN/gamesvr-goldsource-tfc" "./repos/gamesvr-goldsource-tfc"
git_clone "https://github.com/LacledesLAN/gamesvr-hl2dm" "./repos/gamesvr-hl2dm"
git_clone "https://github.com/LacledesLAN/gamesvr-hldms-freeplay" "./repos/gamesvr-hldms-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-ioquake3" "./repos/gamesvr-ioquake3"
git_clone "https://github.com/LacledesLAN/gamesvr-ioquake3-freeplay" "./repos/gamesvr-ioquake3-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-jk2outcast" "./repos/gamesvr-jk2outcast"
git_clone "https://github.com/LacledesLAN/gamesvr-jk2outcast-freeplay" "./repos/gamesvr-jk2outcast-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-minecraft" "./repos/gamesvr-minecraft"
git_clone "https://github.com/LacledesLAN/gamesvr-minecraft-challenge1" "./repos/gamesvr-minecraft-challenge1"
git_clone "https://github.com/LacledesLAN/gamesvr-minecraft-challenge2" "./repos/gamesvr-minecraft-challenge2"
git_clone "https://github.com/LacledesLAN/gamesvr-minecraft-challenge3" "./repos/gamesvr-minecraft-challenge3"
git_clone "https://github.com/LacledesLAN/gamesvr-quake2" "./repos/gamesvr-quake2"
git_clone "https://github.com/LacledesLAN/gamesvr-quake2-freeplay" "./repos/gamesvr-quake2-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-tf2" "./repos/gamesvr-tf2"
git_clone "https://github.com/LacledesLAN/gamesvr-tf2-blindfrag" "./repos/gamesvr-tf2-blindfrag"
git_clone "https://github.com/LacledesLAN/gamesvr-tf2-freeplay" "./repos/gamesvr-tf2-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-tf2classic" "./repos/gamesvr-tf2classic"
git_clone "https://github.com/LacledesLAN/gamesvr-tf2classic-freeplay" "./repos/gamesvr-tf2classic-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-ut99" "./repos/gamesvr-ut99"
git_clone "https://github.com/LacledesLAN/gamesvr-ut2004" "./repos/gamesvr-ut2004"
git_clone "https://github.com/LacledesLAN/gamesvr-ut2004-freeplay" "./repos/gamesvr-ut2004-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-valheim" "./repos/XXgamesvr-valheimXX"
#git_clone "https://github.com/LacledesLAN/gamesvr-valheim-freeplay" "./repos/gamesvr-valheim-freeplay"
git_clone "https://github.com/LacledesLAN/gamesvr-warsow" "./repos/gamesvr-warsow"
git_clone "https://github.com/LacledesLAN/gamesvr-warsow-freeplay" "./repos/gamesvr-warsow-freeplay"

# Utilities
git_clone "https://github.com/LacledesLAN/SteamCMD" "./repos/SteamCMD"

# Dependency Mirros
git_clone "https://github.com/LacledesLAN/amxmodx" "./repos/amxmodx"
git_clone "https://github.com/LacledesLAN/sourcemod.linux" "./repos/sourcemod.linux"
git_clone "https://github.com/LacledesLAN/sourcemod.windows" "./repos/sourcemod.windows"
git_clone "https://github.com/LacledesLAN/sourcemod-configs" "./repos/sourcemod-configs"

# Sources
git_clone "https://github.com/alliedmodders/amxmodx" "./sources/alliedmodders-amxmodx"
git_clone "https://github.com/alliedmodders/metamod-source" "./sources/alliedmodders-metamod-source"
git_clone "https://github.com/alliedmodders/sourcemod" "./sources/alliedmodders-sourcemod"
git_clone "https://github.com/splewis/get5" "./sources/splewis-get5"
